image: python

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - build
  - test
  - deploy

before_script:
  - python --version
  - pip --version  # For debugging
  - pip install --upgrade pip setuptools wheel  # Ensure pip and setuptools are up-to-date
  - pip install --upgrade build
  - pip install --upgrade twine
  - pip install --upgrade pytest

build:
  stage: build
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*

test:
  stage: test
  script:
    - pip install .
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

deploy:
  stage: deploy
  script:
    - python3 -m twine upload --repository pypi dist/* --non-interactive -p $api_key
  environment: production
  only:
    - main  # Ensure this runs only on the main branch or adjust according to your workflow
